version: '3.3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  madsnorgaard_drupal_db:
    image: mariadb:11
    container_name: madsnorgaard_drupal_db
    env_file:
    - .env
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    volumes:
      - ./data/mysql:/var/lib/mysql
    labels:
      - "traefik.enable=false"
    networks:
      - internal

  phpmyadmin:
    container_name: madsnorgaard_drupal_db_admin
    image: phpmyadmin/phpmyadmin
    env_file:
    - .env
    ports:
      - 9999:80
    restart: always
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASS}"
      PMA_ARBITRARY: "1"
    labels:
      - "traefik.http.routers.madsnorgaard_drupal_phpmyadmin.rule=Host(`phpmyadmin.drupal.madsnorgaard.net`)"
      - "traefik.http.routers.madsnorgaard_drupal_phpmyadmin.tls=true"
      - "traefik.http.routers.madsnorgaard_drupal_phpmyadmin.tls.certresolver=lets-encrypt"
    networks:
      - internal
      - web
    depends_on:
      - madsnorgaard_drupal_db

  drupal:
    container_name: madsnorgaard_drupal
    env_file:
    - .env
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - 9998:80
    working_dir: /opt/drupal
    volumes:
      - ./data:/opt/drupal
      - ./composer.json:/opt/drupal/composer.json
      - ./composer.lock:/opt/drupal/composer.lock
      - ./settings.php:/opt/drupal/web/sites/default/settings.php
      - ./data/drupal/private:/opt/drupal/private
      - ./data/drupal/files:/opt/drupal/web/sites/default/files
      - ./data/drupal/logs:/opt/drupal/logs
    environment:
      COMPOSER_MEMORY_LIMIT: "2G"
      WEBROOT_SITE: "${WEBROOT_SITE}"
      DOMAIN: "${DOMAIN_NAME}"
      TRUSTED_HOST_PATTERNS: "${TRUSTED_HOST_PATTERNS}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      HASH_SALT: "${HASH_SALT}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_PORT: "${REDIS_PORT}"
    # Command to fetch all dependencies of Drupal 10 install.
    # Remove /var/www/html directory and link /opt/web to /var/var/www/.
    # Run Drupal9 install with composer and start Apache.
    command: bash -c "composer install && rm -rf /var/www/html && ln -s /opt/drupal/web /var/www/html && /usr/local/bin/apache2-foreground"
    labels:
      - "traefik.http.routers.madsnorgaard_drupal.rule=Host(`drupal.madsnorgaard.net`)"
      - "traefik.http.routers.madsnorgaard_drupal.tls=true"
      - "traefik.http.routers.madsnorgaard_drupal.tls.certresolver=lets-encrypt"
      - "traefik.http.middlewares.madsnorgaard_drupal-www-https-redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.madsnorgaard_drupal-secure-www-redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.web-www-https-redirect.redirectregex.permanent=true"
      - "traefik.http.routers.drupal.middlewares=web-www-https-redirect"
    networks:
      - internal
      - web
    depends_on:
      - madsnorgaard_drupal_db
      - madsnorgaard_redis

  madsnorgaard_redis:
    image: library/redis:latest
    container_name: madsnorgaard_redis
    volumes:
      - ./data/redis:/data
    command: ["redis-server"]
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 20s
      retries: 10
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  madsnorgaard_solr:
    image: solr:8.11.2
    container_name: madsnorgaard_solr
    ports:
     - "8983:8983"
    volumes:
      - ./data/solr:/var/solr
      - ./solr/madsnorgaard:/opt/solr/server/solr/madsnorgaard
    restart: unless-stopped
    networks:
      - internal
