name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      HASH_SALT: ${{ secrets.HASH_SALT }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      DOMAIN_NAME: drupal.madsnorgaard.net
      TRUSTED_HOST_PATTERNS: drupal.madsnorgaard.net
      WEBROOT_SITE: web
    steps:
      # Checks-out your repository so your job can access it
      - uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo DB_NAME=$DB_NAME >> .env
          echo DB_USER=$DB_USER >> .env
          echo DB_PASS=$DB_PASS >> .env
          echo DB_HOST=$DB_HOST >> .env
          echo HASH_SALT=$HASH_SALT >> .env
          echo REDIS_HOST=$REDIS_HOST >> .env
          echo REDIS_PASSWORD=$REDIS_PASSWORD >> .env
          echo DOMAIN_NAME=$DOMAIN_NAME >> .env
          echo TRUSTED_HOST_PATTERNS=$TRUSTED_HOST_PATTERNS >> .env
          echo WEBROOT_SITE=$WEBROOT_SITE >> .env

      - name: Create Docker network
        run: docker network create web

      - name: Start Docker containers
        run: docker-compose up -d

      - name: Run additional commands
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: build
    env:
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SERVER_IP: ${{ secrets.SERVER_IP }}

    steps:
      - name: Pull Docker images and start Docker containers
        run: |
          echo "Pulling Docker images and starting Docker containers..."
          ssh -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") -p $SSH_PORT $SSH_USERNAME@$SERVER_IP "cd /docker/drupal.madsnorgaard.net; docker-compose pull; docker-compose up -d"

      - name: Drupal updates
        run: |
          echo "Updating Drupal database, importing configuration, and rebuilding cache..."
          ssh -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") -p $SSH_PORT $SSH_USERNAME@$SERVER_IP "cd /docker/drupal.madsnorgaard.net; docker-compose exec -T madsnorgaard_drupal bash -c 'drush updb -y; drush cim -y; drush cr;'"
