name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      HASH_SALT: ${{ secrets.HASH_SALT }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      DOMAIN_NAME: drupal.madsnorgaard.net
      TRUSTED_HOST_PATTERNS: drupal.madsnorgaard.net
      WEBROOT_SITE: web

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo DB_NAME=$DB_NAME >> .env
          echo DB_USER=$DB_USER >> .env
          echo DB_PASS=$DB_PASS >> .env
          echo DB_HOST=$DB_HOST >> .env
          echo HASH_SALT=$HASH_SALT >> .env
          echo REDIS_HOST=$REDIS_HOST >> .env
          echo REDIS_PASSWORD=$REDIS_PASSWORD >> .env
          echo DOMAIN_NAME=$DOMAIN_NAME >> .env
          echo TRUSTED_HOST_PATTERNS=$TRUSTED_HOST_PATTERNS >> .env
          echo WEBROOT_SITE=$WEBROOT_SITE >> .env
      # Creates a Docker network called "web"
      - name: Create Docker network
        run: docker network create web

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: docker-compose up -d

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker images and start Docker containers
        run: |
          echo "Pulling Docker images and starting Docker containers..."
          ssh -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") -p 22022 ${{ secrets.SSH_USERNAME }}@5.189.183.167 "cd /docker/drupal.madsnorgaard.net; docker-compose pull; docker-compose up -d"

      - name: Drupal updates
        run: |
          echo "Updating Drupal database, importing configuration, and rebuilding cache..."
          ssh -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") -p 22022 ${{ secrets.SSH_USERNAME }}@5.189.183.167 "cd /docker/drupal.madsnorgaard.net; docker-compose exec -it madsnorgaard_drupal bash -c 'drush updb -y; drush cim -y; drush cr;'"
